### ISSUE TITLE
Licence Inconsistency

### ISSUE THREAD

**Issue by sirinath** [OpenHFT/Chronicle-Values#13]
The mail license file https://github.com/OpenHFT/Chronicle-Values/blob/master/LICENSE.adoc says ASL 2.0 while all the file headers has been updated LGPL: https://github.com/OpenHFT/Chronicle-Values/commit/20cc558c5132ba75e48649684e86727722492a48

**Comment by sirinath** [comment]
I guess this issue is there in other projects. E.g. https://github.com/OpenHFT/Chronicle-Engine/blob/master/src/main/java/net/openhft/chronicle/engine/Chassis.java

**Comment by sirinath** [comment]
@peter-lawrey @leventov Just to follow up on the issue the the source headers. E.g. https://github.com/OpenHFT/Chronicle-Values/blob/master/src/main/java/net/openhft/chronicle/values/Align.java#L1

**Comment by leventov** [comment]
@sirinath Chronicle Values are still LGPL, they were updated by mistake when most (but not all) Chronicle projects moved to Apache 2.

Chronicle Engine is now Apache 2.

**Comment by sirinath** [comment]
But this file says ASL 2.0: https://github.com/OpenHFT/Chronicle-Values/blob/master/LICENSE.adoc

**Comment by leventov** [comment]
@sirinath thanks, this will be fixed

**Comment by sirinath** [comment]
Also is it possible to consider ASL 2.0?

**Comment by sirinath** [comment]
Also it is possible to but out which library is under which license and a promise that the licensing will not change for the parts under ASL 2.0 so users will not accidentally start suing libraries which are incompatible with licensing policies for a particular project or it does not change mid way into a project.
