### ISSUE TITLE
Something not implemented?

### ISSUE THREAD

**Issue by bensku** [OpenHFT/Chronicle-Values#16]
Basically, this error... http://hastebin.com/amoporufip.pl

I wonder, *what* is not implemented yet, exactly and is it going to be implemented soon?
Contents of my value class: http://hastebin.com/esexezoday.java

Even knowing what I'd need to change in my value class to get it working would help.

**Comment by peter-lawrey** [comment]
What is the error you are seeing?

**Comment by leventov** [comment]
@bensku it seems like a bug, or a usability problem at least. But in your case changing to `max = 4294967295L` might just work, and probably that is what you was intended, if you need "unsigned int". Because the `max` argument of `@Range` is included into the range.

**Comment by bensku** [comment]
It worked, thanks! A bit more useful error message might have helped, though. Closing this...
