### ISSUE TITLE
Primitive fields with atomic operations need to be aligned.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Values#22]
There is code to do this but the alignment is always 1 byte by default.

**Comment by leventov** [comment]
Why? fields with setVolatile or setOrdered need to be aligned, but other kinds of atomic operations are possible by extraction.

**Comment by hft-team-city** [comment]
Released in Chronicle-Values-2.16.1 (https://github.com/OpenHFT/Chronicle-Values/releases/chronicle-values-2.16.1), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
