### ISSUE TITLE
get field with CharSequence type takes a long time

### ISSUE THREAD

**Issue by zhengwei14** [OpenHFT/Chronicle-Values#29]
I have a class contains 
public CharSequence getString(@MaxUtf8Length(1024) CharSequence string);
and other 50+ fields;

I tried 10000000 times to get all of the fields
It cost's 30s when contains this CharSequence field. and only cost's 5s without this field.
Is that normal?

我有一个类，包含50多个属性，其中有一个是长度为1024的 CharSequence， 我试了一下1000万次get每个field，需要30秒的时间，但是去掉这个CharSequence字段后，能够缩减到5秒，不知道是否正常？

**Comment by peter-lawrey** [comment]
This should by much faster when a StringBuilder is provided.

**Comment by tgd** [comment]
Closing this out as no work is planned on this issue at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/
