### ISSUE TITLE
Finished conversion of readme from .md to .adoc

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Values#34]
we updated the ".md" to ".adoc" for consistency and adding of badges for sonarQ,
following on from this update -  most of the documentation is ok, but a few of the links and titles are broken, please fix

**Comment by RobAustin** [comment]
one area that is broken is 
![image](https://user-images.githubusercontent.com/6506056/142986840-4f2603ba-f9a3-4f25-9a13-39554d5e6511.png)

**Comment by j4sm1ne96** [comment]
This has been changed.
