### ISSUE TITLE
Getters/Setters matching name pattern "get__X" and "set__X" cause an error in generation.

### ISSUE THREAD

**Issue by lsubra** [OpenHFT/Chronicle-Values#8]
This is a minor issue, but here it is.

### Stack trace
java.lang.IllegalArgumentException: java.lang.IllegalStateException: Some writing method should be present for field get__PtrFieldName
	at net.openhft.chronicle.values.ValueModel.acquire(ValueModel.java:60)
	at net.openhft.chronicle.values.Values.nativeClassFor(Values.java:82)
	at net.openhft.chronicle.values.Values.newNativeReference(Values.java:50)

### Where: 
1.5.1. Haven't tested other versions

### To reproduce:
1. Create a Value interface a/b/c/X.java
2. Create a getter/setter on X.java: "long get__myPtr()" and "void set__myPtr(long x)".
3. Instantiate 'X', Values.newNativeReference(X.class) and this throws the stack trace above.

### Potential Issue
Looks like https://github.com/OpenHFT/Chronicle-Values/blob/chronicle-values-1.5.1/src/main/java/net/openhft/chronicle/values/CodeTemplate.java#L64 regex matches with field name "get__myPtr" so the setter expects "get__myPtr" instead of "set__myPtr" !

### My use case
I needed this strange naming convention to hide these methods in my IDE. They hold native pointer values and I don't need them since I dereference the pointer via a "getMyPointedObject()" method in the same interface (via a default method). i.e I have "long get__myPtr()", "void set__myPtr(long)" and "default MyObject getMyPointerObect()".

### Workarounds
Many. So, this is low priority.

**Comment by leventov** [comment]
Thanks. Fixed by just allowing field names start with underscores. The fix should be available in the next released version.
